### ISSUE TITLE
Display bad data message

### ISSUE THREAD

**Issue by over140** [MixinNetwork/mips#10]
if user fail to parse the message data, you cannot directly abandon the data away, you need to remind the user to upgrade the app or feedback to developer.

**Comment by cedricfung** [comment]
Unknown and bad data are two different things, unknown message category could be fixed by upgrading the app, but bad data may not be.

So there should be two different messages.

**Comment by isdot** [comment]
https://github.com/MixinNetwork/desktop-app/pull/573

**Comment by over140** [comment]
https://github.com/MixinNetwork/ios-app/pull/483
https://github.com/MixinNetwork/ios-app/pull/492

**Comment by SeniorZhai** [comment]
https://github.com/MixinNetwork/android-app/pull/1381
