### ISSUE TITLE
Dim the unread number indicator of muted conversations

### ISSUE THREAD

**Issue by cedricfung** [MixinNetwork/mips#14]
If a conversation is muted, the unread number is still bright blue, which makes it difficult to find important unread conversations in the list.

**Comment by SeniorZhai** [comment]
https://github.com/MixinNetwork/android-app/pull/1396

**Comment by isdot** [comment]
https://github.com/MixinNetwork/desktop-app/pull/583

**Comment by over140** [comment]
https://github.com/MixinNetwork/ios-app/commit/a0a9b8804373a1d617b7857957db3b65c2fc8960
