### ISSUE TITLE
hCaptcha replace reCAPTCHA

### ISSUE THREAD

**Issue by crossle** [MixinNetwork/mips#22]
Use hCaptcha protects user privacy

https://docs.hcaptcha.com/invisible

https://medium.com/@hCaptcha/how-to-use-hcaptcha-with-android-apps-bb546c610bc4

**Comment by cedricfung** [comment]
Maybe we should use both hCaptcha and reCAPTCHA for better compatibilities. Sometimes one of them may be outage for some regions, we could try one by one.

**Comment by crossle** [comment]
Another method, client try load hCaptcha if reCAPTCHA load failed.

**Comment by crossle** [comment]
DONE.
