### ISSUE TITLE
Universal transfer URI

### ISSUE THREAD

**Issue by cedricfung** [MixinNetwork/mips#9]
Extend the `mixin://pay?` scheme to support some other popular blockchain schemes.

> bitcoin:1zgmvYi5x1wy3hUh7AjKgpcVgpA8Lj9FA?recipient=773e5e77-4107-45c2-b648-8fc722ed77f5&asset=c6d0c728-2624-429b-8e0d-d9d19b6592fa&amount=0.23

When Mixin Messenger find a valid scheme prefix `bitcion:`, it should parse the URI to locate `recipient`, `asset` and `amount`, then open the Transfer Bottom Sheet. The URI parse logic and params should be identical to `mixin://pay?` URI.

All available scheme prefixes are "bitcoin:", "bitcoincash:", "bitcoinsv:", "ethereum:", "litecoin:", "dash:", "ripple:", "zcash:", "horizen:", "monero:", "binancecoin:", "stellar:".

**Comment by over140** [comment]
https://github.com/MixinNetwork/ios-app/blob/c39ccd70f2f2e9435a5e4e4a860aa58de9f56e36/Mixin/UserInterface/Windows/UrlWindow.swift#L48

**Comment by over140** [comment]
The optional parameter **memo** can be supported, like this:
`
bitcoin:1zgmvYi5x1wy3hUh7AjKgpcVgpA8Lj9FA?recipient=773e5e77-4107-45c2-b648-8fc722ed77f5&asset=c6d0c728-2624-429b-8e0d-d9d19b6592fa&amount=0.23&memo=Thinks
`

**Comment by over140** [comment]
https://github.com/MixinNetwork/ios-app/commit/b4d78c8777eb768a3db044b2a669a8d3e327b9eb
